import type { Product } from './types';

export const products: Product[] = [
  {
    id: '1',
    name: 'Artisanal Sourdough',
    description: 'Freshly baked sourdough with a crispy crust and soft, chewy interior. Perfect for sandwiches or toast.',
    price: 6.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Bakery',
    featured: true,
    dataAiHint: 'sourdough bread',
  },
  {
    id: '2',
    name: 'Organic Avocados',
    description: 'A set of three creamy, ripe Hass avocados, grown organically and picked at their peak.',
    price: 4.50,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Produce',
    featured: true,
    dataAiHint: 'ripe avocados',
  },
  {
    id: '3',
    name: 'Farmstead Cheddar',
    description: 'A sharp, aged white cheddar cheese block, handcrafted from grass-fed cow\'s milk. Aged for 12 months.',
    price: 12.00,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Dairy',
    featured: true,
    dataAiHint: 'cheddar cheese',
  },
  {
    id: '4',
    name: 'Grass-Fed Ground Beef',
    description: 'One pound of lean, 90/10 grass-fed ground beef. No added hormones or antibiotics.',
    price: 9.75,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Meat',
    dataAiHint: 'ground beef',
  },
  {
    id: '5',
    name: 'Heirloom Tomatoes',
    description: 'A vibrant mix of colorful and flavorful heirloom tomatoes, perfect for salads and sauces.',
    price: 5.25,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Produce',
    dataAiHint: 'heirloom tomatoes',
  },
  {
    id: '6',
    name: 'Whole-Grain Oats',
    description: '24oz container of organic, gluten-free rolled oats. An excellent source of fiber for a healthy breakfast.',
    price: 7.50,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Pantry',
    dataAiHint: 'oats breakfast',
  },
  {
    id: '7',
    name: 'Chocolate Croissants',
    description: 'A pack of four flaky, buttery croissants filled with rich, dark chocolate. Baked fresh daily.',
    price: 8.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Bakery',
    dataAiHint: 'chocolate croissants',
  },
  {
    id: '8',
    name: 'Organic Free-Range Eggs',
    description: 'One dozen large brown eggs from free-range chickens fed an all-organic, vegetarian diet.',
    price: 6.20,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Dairy',
    featured: true,
    dataAiHint: 'carton eggs',
  },
  {
    id: '9',
    name: 'Extra Virgin Olive Oil',
    description: 'Cold-pressed extra virgin olive oil in a 500ml bottle. Robust and peppery flavor.',
    price: 15.00,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Pantry',
    featured: true,
    dataAiHint: 'olive oil',
  },
  {
    id: '10',
    name: 'Wild-Caught Salmon',
    description: 'Two 6oz fillets of fresh, wild-caught Sockeye salmon. Rich in Omega-3s and flavor.',
    price: 22.50,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Meat',
    featured: true,
    dataAiHint: 'salmon fillet',
  },
  {
    id: '11',
    name: 'Fresh Berry Mix',
    description: 'A pint of mixed organic strawberries, blueberries, and raspberries. Sweet and antioxidant-rich.',
    price: 6.80,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Produce',
    dataAiHint: 'mixed berries',
  },
  {
    id: '12',
    name: 'Almond Milk Yogurt',
    description: 'A 16oz tub of creamy, unsweetened plain yogurt made from almonds. A great dairy-free alternative.',
    price: 5.99,
    imageUrl: 'https://placehold.co/600x400.png',
    category: 'Dairy',
    dataAiHint: 'yogurt bowl',
  },
];
